import { Country } from "../../shared/services/country.service";

//names have to match translation labels
export const COUNTRIES: Country[] = [
    { name: 'spain', phoneCode: '34', isoCountryCode: 'ES' },
    { name: 'germany', phoneCode: '49', isoCountryCode: 'DE' },
    { name: 'france', phoneCode: '33', isoCountryCode: 'FR' },
    { name: 'italy', phoneCode: '39', isoCountryCode: 'IT' },
    { name: 'unitedKingdom', phoneCode: '44', isoCountryCode: 'GB' },
    { name: 'russia', phoneCode: '7', isoCountryCode: 'RU' },
    { name: 'ukraine', phoneCode: '380', isoCountryCode: 'UA' },
    { name: 'poland', phoneCode: '48', isoCountryCode: 'PL' },
    { name: 'romania', phoneCode: '40', isoCountryCode: 'RO' },
    { name: 'netherlands', phoneCode: '31', isoCountryCode: 'NL' },
    { name: 'belgium', phoneCode: '32', isoCountryCode: 'BE' },
    { name: 'greece', phoneCode: '30', isoCountryCode: 'GR' },
    { name: 'portugal', phoneCode: '351', isoCountryCode: 'PT' },
    { name: 'sweden', phoneCode: '46', isoCountryCode: 'SE' },
    { name: 'norway', phoneCode: '47', isoCountryCode: 'NO' },
    { name: 'albania', phoneCode: '355', isoCountryCode: 'AL' },
    { name: 'andorra', phoneCode: '376', isoCountryCode: 'AD' },
    { name: 'armenia', phoneCode: '374', isoCountryCode: 'AM' },
    { name: 'austria', phoneCode: '43', isoCountryCode: 'AT' },
    { name: 'azerbaijan', phoneCode: '994', isoCountryCode: 'AZ' },
    { name: 'belarus', phoneCode: '375', isoCountryCode: 'BY' },
    { name: 'bosniaAndHerzegovina', phoneCode: '387', isoCountryCode: 'BA' },
    { name: 'bulgaria', phoneCode: '359', isoCountryCode: 'BG' },
    { name: 'croatia', phoneCode: '385', isoCountryCode: 'HR' },
    { name: 'cyprus', phoneCode: '357', isoCountryCode: 'CY' },
    { name: 'czechRepublic', phoneCode: '420', isoCountryCode: 'CZ' },
    { name: 'denmark', phoneCode: '45', isoCountryCode: 'DK' },
    { name: 'estonia', phoneCode: '372', isoCountryCode: 'EE' },
    { name: 'finland', phoneCode: '358', isoCountryCode: 'FI' },
    { name: 'georgia', phoneCode: '995', isoCountryCode: 'GE' },
    { name: 'hungary', phoneCode: '36', isoCountryCode: 'HU' },
    { name: 'iceland', phoneCode: '354', isoCountryCode: 'IS' },
    { name: 'ireland', phoneCode: '353', isoCountryCode: 'IE' },
    { name: 'kazakhstan', phoneCode: '7', isoCountryCode: 'KZ' },
    { name: 'kosovo', phoneCode: '383', isoCountryCode: 'XK' },
    { name: 'latvia', phoneCode: '371', isoCountryCode: 'LV' },
    { name: 'liechtenstein', phoneCode: '423', isoCountryCode: 'LI' },
    { name: 'lithuania', phoneCode: '370', isoCountryCode: 'LT' },
    { name: 'luxembourg', phoneCode: '352', isoCountryCode: 'LU' },
    { name: 'malta', phoneCode: '356', isoCountryCode: 'MT' },
    { name: 'moldova', phoneCode: '373', isoCountryCode: 'MD' },
    { name: 'monaco', phoneCode: '377', isoCountryCode: 'MC' },
    { name: 'montenegro', phoneCode: '382', isoCountryCode: 'ME' },
    { name: 'northMacedonia', phoneCode: '389', isoCountryCode: 'MK' },
    { name: 'sanMarino', phoneCode: '378', isoCountryCode: 'SM' },
    { name: 'serbia', phoneCode: '381', isoCountryCode: 'RS' },
    { name: 'slovakia', phoneCode: '421', isoCountryCode: 'SK' },
    { name: 'slovenia', phoneCode: '386', isoCountryCode: 'SI' },
    { name: 'switzerland', phoneCode: '41', isoCountryCode: 'CH' },
    { name: 'turkey', phoneCode: '90', isoCountryCode: 'TR' },
    { name: 'vaticanCity', phoneCode: '379', isoCountryCode: 'VA' }
];
