name: Release
on:
  push:
    branches:
      - features/cicd-aws

permissions:
  contents: write

jobs:
  
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: local
    env:
      AMPLIFY_APP_NAME: issuer-ui
      BRANCH_NAME: main
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Npm Build
        run: npm run build -- --output-path=./dist/out --configuration "production"

      # create a zip file of the dist folder
      - name: Create Zip File
        run: |
          ZIP_FILE="dist/out.zip"
          zip -r $ZIP_FILE dist/out
          echo "ZIP_FILE=$ZIP_FILE" >> $GITHUB_ENV
      
      - name: Configure AWS Credentials  
        uses: aws-actions/configure-aws-credentials@v2  
        with:  
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}  
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
          aws-region:            'eu-west-1'    

      - name: Extract Amplify App ID
        run: |
          AMPLIFY_APP_ID=$(aws amplify list-apps --query "apps[?name=='${{ env.AMPLIFY_APP_NAME }}'].appId" --output text)
          echo "AMPLIFY_APP_ID=$AMPLIFY_APP_ID" >> $GITHUB_ENV
          echo "Found App ID: $AMPLIFY_APP_ID for app: ${{ env.AMPLIFY_APP_NAME }}"
      
      - name: Create AWS Amplify Deployment
        run: |
          read ZIP_UPLOAD_URL JOB_ID <<< $(aws amplify create-deployment --app-id ${{ env.AMPLIFY_APP_ID }} --branch-name ${{ env.BRANCH_NAME }} --file-map ${{ env.ZIP_FILE }} --query 'join(` `, [zipUploadUrl, jobId])' --output text)
          curl -X PUT --upload-file ${{ env.ZIP_FILE }} "$ZIP_UPLOAD_URL"
          aws amplify start-deployment --app-id ${{ env.AMPLIFY_APP_ID }} --branch-name ${{ env.BRANCH_NAME }} --job-id $JOB_ID       

      - name: Notify Deployment
        run: |
          echo "Deployment started for version ${{ env.VERSION }}. Check the AWS Amplify console for progress."
          echo "Deployment URL: https://${{ env.JOB_ID }}.amplifyapp.com"
